<#
Safe Workspace MCP - portable Windows launcher.
Downloads the pinned OpenAI Secure MCP Tunnel client (SHA-256 verified), generates
a runtime config for one workspace, and runs the packaged MCP server as a stdio
child of tunnel-client in the foreground. No admin rights, no PATH/registry
changes, no Python/Git/Node required. Press Ctrl+C to stop.
Usage: .\Start-SafeWorkspaceMCP.ps1 -Workspace "D:\My Workspace\demo" -TunnelId "tunnel_..."
#>

[CmdletBinding()]
param(
    [string]$Workspace,
    [string]$TunnelId,
    [switch]$CreateWorkspace,
    [string]$TunnelClientPath,
    [string]$StateRoot,
    [switch]$DryRun
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version 2.0

$TunnelClientVersion = 'v0.0.11'
$TunnelClientBaseUrl = "https://github.com/openai/tunnel-client/releases/download/$TunnelClientVersion"
$TunnelClientAssets = @{
    'AMD64' = @{
        File   = "tunnel-client-$TunnelClientVersion-windows-amd64.zip"
        SHA256 = 'EB912C86C6CCDE90CDA805CB17009507176A656725CF86C36FABE1901A12E29B'
    }
    'ARM64' = @{
        File   = "tunnel-client-$TunnelClientVersion-windows-arm64.zip"
        SHA256 = '38F015A720404C8CCD5976A0D6AED18D931899697EAF208548B5EB3D0F6E8592'
    }
}

function ConvertTo-TomlBasicString {
    param([Parameter(Mandatory = $true)][string]$Value)
    $escaped = $Value.Replace('\', '\\').Replace('"', '\"')
    return '"' + $escaped + '"'
}

function ConvertTo-TunnelClientArg {
    param([Parameter(Mandatory = $true)][string]$Path)
    if ($Path.IndexOf("'") -lt 0) {
        return "'" + $Path + "'"
    }
    $escaped = $Path.Replace('\', '\\').Replace('"', '\"')
    return '"' + $escaped + '"'
}

function Test-TunnelClientId {
    param([Parameter(Mandatory = $true)][string]$Id)
    return ($Id -cmatch '^tunnel_[0-9a-f]{32}$')
}

function Test-FileSha256 {
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [Parameter(Mandatory = $true)][string]$ExpectedSha256
    )
    $actual = (Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash
    return ($actual -ceq $ExpectedSha256)
}

function Get-ConfigPathForWorkspace {
    param([Parameter(Mandatory = $true)][string]$WorkspaceFullPath, [Parameter(Mandatory = $true)][string]$RuntimeDir)
    $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
    $pathBytes = $utf8NoBom.GetBytes($WorkspaceFullPath.ToLowerInvariant())
    $sha = [System.Security.Cryptography.SHA256]::Create()
    try {
        $hashBytes = $sha.ComputeHash($pathBytes)
    }
    finally {
        $sha.Dispose()
    }
    $hex = [System.BitConverter]::ToString($hashBytes).Replace('-', '').Substring(0, 16).ToLowerInvariant()
    return (Join-Path $RuntimeDir "config-$hex.toml")
}

function Write-RuntimeConfig {
    param(
        [Parameter(Mandatory = $true)][string]$ConfigPath,
        [Parameter(Mandatory = $true)][string]$WorkspaceRoot
    )
    $posixRoot = $WorkspaceRoot.Replace('\', '/')
    $content = "# Generated by Start-SafeWorkspaceMCP.ps1`n[workspace]`nroot = $(ConvertTo-TomlBasicString $posixRoot)`n`n[server]`ntransport = `"stdio`"`n"
    $dir = Split-Path -Parent $ConfigPath
    if (-not (Test-Path -LiteralPath $dir -PathType Container)) {
        New-Item -ItemType Directory -Path $dir -Force | Out-Null
    }
    [System.IO.File]::WriteAllText($ConfigPath, $content, (New-Object System.Text.UTF8Encoding($false)))
}

function Get-TunnelClientAssetInfo {
    $arch = $env:PROCESSOR_ARCHITECTURE
    if (-not $TunnelClientAssets.ContainsKey($arch)) {
        throw "Unsupported processor architecture: $arch (supported: $($TunnelClientAssets.Keys -join ', '))"
    }
    return $TunnelClientAssets[$arch]
}

function Ensure-TunnelClient {
    param([Parameter(Mandatory = $true)][string]$ToolsRoot)
    if (-not [string]::IsNullOrWhiteSpace($TunnelClientPath)) {
        # Advanced operator override: the operator vouches for this binary.
        # The pinned-SHA256 download guarantee is intentionally skipped; we
        # only require that the target exists and reports a usable version.
        if (-not (Test-Path -LiteralPath $TunnelClientPath -PathType Leaf)) {
            throw "TunnelClientPath not found: $TunnelClientPath"
        }
        $probeOk = $false
        $probe = $null
        $oldEap = $ErrorActionPreference
        $ErrorActionPreference = 'Continue'
        try {
            $probe = & $TunnelClientPath --version 2>$null
            $probeOk = ($LASTEXITCODE -eq 0)
        }
        catch {
            $probeOk = $false
        }
        finally {
            $ErrorActionPreference = $oldEap
        }
        if (-not $probeOk -or [string]::IsNullOrWhiteSpace((@($probe) -join ' '))) {
            throw ("TunnelClientPath does not execute correctly (--version check failed): " + `
                "$TunnelClientPath. The pinned SHA-256 download guarantee is only " + `
                'available without -TunnelClientPath.')
        }
        Write-Host "[Safe Workspace MCP] ADVANCED OVERRIDE: using operator-provided tunnel-client (pinned SHA-256 guarantee skipped): $TunnelClientPath"
        Write-Host "[Safe Workspace MCP] tunnel-client --version: $((@($probe) | Select-Object -First 1))"
        return $TunnelClientPath
    }

    $exePath = Join-Path $ToolsRoot "$TunnelClientVersion\tunnel-client.exe"
    if (Test-Path -LiteralPath $exePath -PathType Leaf) {
        Write-Host "[Safe Workspace MCP] Reusing cached tunnel-client $TunnelClientVersion"
        return $exePath
    }

    $asset = Get-TunnelClientAssetInfo
    $zipUrl = "$TunnelClientBaseUrl/$($asset.File)"
    $versionDir = Join-Path $ToolsRoot $TunnelClientVersion
    New-Item -ItemType Directory -Path $versionDir -Force | Out-Null
    $zipPath = Join-Path $versionDir $asset.File

    Write-Host "[Safe Workspace MCP] Downloading tunnel-client $TunnelClientVersion from the official OpenAI release..."
    [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor [System.Net.SecurityProtocolType]::Tls12
    $oldProgress = $ProgressPreference
    $ProgressPreference = 'SilentlyContinue'
    try {
        Invoke-WebRequest -Uri $zipUrl -OutFile $zipPath -UseBasicParsing
    }
    catch {
        if (Test-Path -LiteralPath $zipPath) { Remove-Item -LiteralPath $zipPath -Force }
        throw "Failed to download tunnel-client: $($_.Exception.Message)"
    }
    finally {
        $ProgressPreference = $oldProgress
    }

    if (-not (Test-FileSha256 -Path $zipPath -ExpectedSha256 $asset.SHA256)) {
        Remove-Item -LiteralPath $zipPath -Force
        throw "SHA-256 verification FAILED for $asset.File (expected $($asset.SHA256)). Download discarded; refusing to continue."
    }
    Write-Host "[Safe Workspace MCP] SHA-256 verified against the pinned official checksum."

    $extractDir = Join-Path $versionDir 'extracted'
    if (Test-Path -LiteralPath $extractDir) { Remove-Item -LiteralPath $extractDir -Recurse -Force }
    Expand-Archive -LiteralPath $zipPath -DestinationPath $extractDir -Force
    Remove-Item -LiteralPath $zipPath -Force

    $found = Get-ChildItem -LiteralPath $extractDir -Recurse -Filter 'tunnel-client.exe' | Select-Object -First 1
    if ($null -eq $found) {
        throw "tunnel-client.exe not found inside the verified archive."
    }
    $exePath = Join-Path $versionDir 'tunnel-client.exe'
    Move-Item -LiteralPath $found.FullName -Destination $exePath -Force
    Remove-Item -LiteralPath $extractDir -Recurse -Force
    Write-Host "[Safe Workspace MCP] tunnel-client $TunnelClientVersion installed."
    return $exePath
}

function Resolve-WorkspacePath {
    param([Parameter(Mandatory = $true)][string]$InputPath)
    $trimmed = $InputPath.Trim()
    if ($trimmed.Length -ge 2 -and $trimmed[0] -eq $trimmed[$trimmed.Length - 1] -and ($trimmed[0] -eq '"' -or $trimmed[0] -eq "'")) {
        $trimmed = $trimmed.Substring(1, $trimmed.Length - 2)
    }
    if ($trimmed -match '[\x00-\x1f]') {
        throw "Workspace path contains control characters."
    }
    $full = [System.IO.Path]::GetFullPath($trimmed)
    if (Test-Path -LiteralPath $full -PathType Container) {
        return $full
    }
    if ($CreateWorkspace) {
        New-Item -ItemType Directory -Path $full -Force | Out-Null
        Write-Host "[Safe Workspace MCP] Created workspace directory: $full"
        return $full
    }
    throw "Workspace directory not found: $full (create it first, or pass -CreateWorkspace)"
}

function Read-SecretFromSecureString {
    param([Parameter(Mandatory = $true)][System.Security.SecureString]$Secure)
    $bstr = [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($Secure)
    try {
        return [System.Runtime.InteropServices.Marshal]::PtrToStringBSTR($bstr)
    }
    finally {
        [System.Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstr)
    }
}

function Main {
    Write-Host "[Safe Workspace MCP] Portable launcher (tunnel-client pin: $TunnelClientVersion)"

    if ([string]::IsNullOrWhiteSpace($Workspace)) {
        $Workspace = Read-Host 'Workspace directory (fixed single workspace for this run)'
    }
    $workspacePath = Resolve-WorkspacePath -InputPath $Workspace

    # Note: .git ownership (managed vs foreign) is decided solely by the MCP
    # core at startup; the launcher intentionally does NOT pre-check .git.

    if ([string]::IsNullOrWhiteSpace($TunnelId)) {
        if (-not [string]::IsNullOrWhiteSpace($env:CONTROL_PLANE_TUNNEL_ID)) {
            $TunnelId = $env:CONTROL_PLANE_TUNNEL_ID
        }
        else {
            $TunnelId = (Read-Host 'OpenAI Secure MCP Tunnel ID (tunnel_...)').Trim()
        }
    }
    if (-not (Test-TunnelClientId -Id $TunnelId)) {
        Write-Host 'A tunnel ID looks like: tunnel_0123456789abcdef0123456789abcdef'
        Write-Host 'Please create a Secure MCP Tunnel first: https://platform.openai.com/settings/organization/tunnels'
        throw 'Missing or malformed tunnel ID.'
    }

    $apiKeySetByUs = $false
    $apiKey = $null
    if ([string]::IsNullOrWhiteSpace($env:CONTROL_PLANE_API_KEY)) {
        if ($DryRun) {
            Write-Host '[Safe Workspace MCP] DryRun: CONTROL_PLANE_API_KEY not set; it will be prompted at real launch.'
        }
        else {
            $secure = Read-Host 'OpenAI Runtime API Key (input hidden)' -AsSecureString
            $apiKey = Read-SecretFromSecureString -Secure $secure
            if ([string]::IsNullOrWhiteSpace($apiKey)) {
                Write-Host 'Create a Runtime API Key here: https://platform.openai.com/settings/organization/api-keys'
                throw 'Runtime API Key is required.'
            }
        }
    }

    $scriptDir = Split-Path -Parent $PSCommandPath
    $mcpExe = Join-Path $scriptDir 'safe-workspace-mcp\safe-workspace-mcp.exe'
    if (-not (Test-Path -LiteralPath $mcpExe -PathType Leaf)) {
        throw "Packaged server not found: $mcpExe (run this script from the extracted release folder)"
    }

    if ([string]::IsNullOrWhiteSpace($StateRoot)) {
        $StateRoot = Join-Path -Path $env:LOCALAPPDATA -ChildPath 'SafeWorkspaceMCP'
    }
    $toolsRoot = Join-Path -Path $StateRoot -ChildPath 'tools\tunnel-client'
    $runtimeDir = Join-Path -Path $StateRoot -ChildPath 'runtime'
    foreach ($d in @($toolsRoot, $runtimeDir)) {
        if (-not (Test-Path -LiteralPath $d -PathType Container)) {
            New-Item -ItemType Directory -Path $d -Force | Out-Null
        }
    }

    $configPath = Get-ConfigPathForWorkspace -WorkspaceFullPath $workspacePath -RuntimeDir $runtimeDir
    Write-RuntimeConfig -ConfigPath $configPath -WorkspaceRoot $workspacePath

    $mcpCommand = (ConvertTo-TunnelClientArg -Path $mcpExe) + ' ' + (ConvertTo-TunnelClientArg -Path $configPath)

    Write-Host "[Safe Workspace MCP] Workspace : $workspacePath"
    Write-Host "[Safe Workspace MCP] Config    : $configPath"
    Write-Host "[Safe Workspace MCP] Tunnel ID : $TunnelId"

    if ($DryRun) {
        # Show the intended command without any download or version probe.
        if (-not [string]::IsNullOrWhiteSpace($TunnelClientPath)) {
            $tunnelExe = $TunnelClientPath
            Write-Host "[Safe Workspace MCP] DryRun: ADVANCED OVERRIDE would be used (pinned SHA-256 guarantee skipped): $TunnelClientPath"
        }
        else {
            $tunnelExe = Join-Path $toolsRoot "$TunnelClientVersion\tunnel-client.exe"
            Write-Host "[Safe Workspace MCP] DryRun: first real run downloads/verifies tunnel-client $TunnelClientVersion if not cached."
        }
        Write-Host "[Safe Workspace MCP] DryRun: would start:"
        Write-Host "  `"$tunnelExe`" run --mcp.command `"$mcpCommand`""
        return
    }

    $tunnelExe = Ensure-TunnelClient -ToolsRoot $ToolsRoot

    if ($null -ne $apiKey) {
        $env:CONTROL_PLANE_API_KEY = $apiKey
        $apiKeySetByUs = $true
        $apiKey = $null
    }
    $env:CONTROL_PLANE_TUNNEL_ID = $TunnelId

    Write-Host '[Safe Workspace MCP] Starting tunnel-client in the foreground (Ctrl+C to stop)...'
    $exitCode = 1
    # tunnel-client logs structured INFO lines to stderr. Under output
    # redirection (2>&1, pipes, CI capture), Windows PowerShell 5.1 turns
    # native stderr into ErrorRecords; with ErrorActionPreference=Stop that
    # would kill the launcher on the first log line. Relax EAP around the
    # foreground run only (same pattern as the --version probe).
    $oldEap = $ErrorActionPreference
    $ErrorActionPreference = 'Continue'
    try {
        & $tunnelExe run --mcp.command $mcpCommand
        $exitCode = $LASTEXITCODE
        if ($null -eq $exitCode) { $exitCode = 0 }
    }
    finally {
        $ErrorActionPreference = $oldEap
        if ($apiKeySetByUs) {
            Remove-Item Env:\CONTROL_PLANE_API_KEY -ErrorAction SilentlyContinue
        }
        Remove-Item Env:\CONTROL_PLANE_TUNNEL_ID -ErrorAction SilentlyContinue
    }

    Write-Host ''
    Write-Host "[Safe Workspace MCP] tunnel-client exited (code $exitCode)."
    Write-Host '[Safe Workspace MCP] Safe Workspace MCP was running through tunnel:'
    Write-Host "  $TunnelId"
    Write-Host '  Connect this existing tunnel from ChatGPT Developer Mode.'
    Write-Host '  No ChatGPT or Codex settings were modified.'
}

Main
